// File generated by FlutterFire CLI / filled in manually.
// Replace every YOUR_... value with the values from:
//   Firebase Console → Project Settings → Your apps → SDK setup & configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  // ── Web ─────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey:            'AIzaSyDoWdw24gMPGGa0zM8WSARGCSsVsCbWUlc',
    appId:             '1:982871293951:web:5f925d8fd453ceb9c5f1ca',
    messagingSenderId: '982871293951',
    projectId:         'subinsights-df0dc',
    authDomain:        'subinsights-df0dc.firebaseapp.com',
    storageBucket:     'subinsights-df0dc.firebasestorage.app',
    measurementId:     'G-7RQXGJVDV3',
  );

  // ── Android ─────────────────────────────────────────────────────────────
  // Download google-services.json from Firebase Console and run
  // `flutterfire configure` to populate these automatically.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            'YOUR_ANDROID_API_KEY',
    appId:             'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId:         'YOUR_PROJECT_ID',
    storageBucket:     'YOUR_PROJECT_ID.appspot.com',
  );

  // ── iOS ──────────────────────────────────────────────────────────────────
  // Download GoogleService-Info.plist from Firebase Console and run
  // `flutterfire configure` to populate these automatically.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:            'YOUR_IOS_API_KEY',
    appId:             'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId:         'YOUR_PROJECT_ID',
    storageBucket:     'YOUR_PROJECT_ID.appspot.com',
    iosBundleId:       'com.subinsights.app',
  );
}
